name: hound_blog
version: 0.0.1
description: Static blog website transformer
dependencies:
  barback: '>=0.15.2+2 <0.16.0'
  mustache4dart: '>= 1.0.0 < 2.0.0'
  path: '>=1.3.0 <1.4.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
